## Exercise 1

Give three real-world examples of different types of cognitive bias.

- Confirmation Bias
Confirmation bias is people's tendancy to seek out information to support their beliefs whilst ignoring information that do not support their ideas, also selectively interpreting and remember information that supports their views whilst discounting information that disproves their ideals (Cherry, 2022).

A real-world example is the poor decision making in investing in cyptocurrency during the pandemic that I think many of us were guilty of. After the dramatic rise in price of GameStop stocks and Bitcoin, many was drawn into the world of cyptocurrency. With a large number of individuals boasting about how much money they have made in such a small time, many people's mind was made up that cypto was stable investment, any negative information or anicdotes of a failed investiment was deemed as bad luck.

- Authority Bias
Another common type of cognitive bias is authority bias, where an individual is influenced by the opinions or actions of an figure of authority. Placing trust and base decision making depending on those who are deemed to be an expert (Morgia, 2022).

A real-world example of this cognitive bias is how easy people are influenced on how to act and what to buy by social media influencers. The Kardashians famously endorsed "Fit Tea" glamorously on their social media for their millions of followers. The tea actually does more harm than good, they failed to mention the many negative side effects from consuming the product. Many of their loyal fans would have bought the product without a second thought.


- Overconfidence bias
Overconfidence bias is when a person overestimate their abilites, to think that their judgement is more realiable. This can lead to unethical behaviors and decision making (Willows, 2020).

A real-world example of this type of cognitive bias is when a doctor come to a quick diagnoses of a patients symptoms, propose a treatment plan without consulting their peers and discouraging a patient to seek a second opinion from another doctor. The doctor may have years of experience on this issue but they can't be certain that they know everything on the condition/disease in question.

## Exercise 2

Show that the difference between the standard deviation calculations is greatest for small sample sizes.

Standard deviation measures how the sample values spread in relation of the mean value. SD cannot be a negative number. If it is close to 0 or equal to 0, this shows that sample values are close to the mean. To calculate the standard deviation, we must first determine the mean of the sample values.


In [2]:
# import libraries.
import numpy as np
import matplotlib.pyplot as plt

In [10]:
# Code found in Topic 3 Bessel's Correction video.
# randomly generating a small(10) sample of values with size 5 and a standard deviation of 3.
sample1 = np.random.normal(0,3,(10,5))
sample1

array([[ 0.81198131, -1.60765527,  3.09269303,  2.68490156,  2.59145596],
       [ 0.8148576 ,  1.51433722, -1.41657862, -1.17072566, -0.51112885],
       [ 1.23954218,  1.75600959, -0.27456731,  0.30134457,  0.19538446],
       [ 0.77596749, -2.53919534,  4.69943338, -1.11432522,  1.02317523],
       [ 0.33063046, -2.30613274,  0.2657463 ,  0.14859466,  2.50301216],
       [-3.1875477 , -3.76281801,  6.29500531, -0.5239248 , -1.78304489],
       [ 1.80395325,  0.00824256, -3.77943109,  0.94686807, -3.05228479],
       [-1.97342366,  4.63112402, -2.84258985,  2.15062023,  1.8354594 ],
       [ 4.25801511,  2.74376938,  2.03727118, -2.7228116 , -1.22313809],
       [ 2.79980521, -0.99395687,  2.95017707, -1.60592579, -1.96022271]])

In [11]:
# calculate standard deviation of small sample.
stdevs = sample1.std(axis=1)
stdevs

array([1.74709777, 1.1381925 , 0.74211446, 2.44147712, 1.52367447,
       3.62339669, 2.21061608, 2.7758349 , 2.58964326, 2.1757166 ])

In [12]:
# randomly generating a large(100) sample of values with size 5 and a standard deviation of 3.
sample2 = np.random.normal(0,3,(100,5))
sample2

array([[-7.74276694e-01,  1.30701526e+00,  3.05290352e+00,
        -4.00142362e+00, -1.87104405e+00],
       [-6.38610576e+00,  8.87260340e-01, -4.56207400e+00,
        -8.03131220e-01,  1.10996576e+00],
       [-6.43682469e-02,  3.31594774e+00,  1.52311332e+00,
        -7.69252259e+00, -4.72938152e+00],
       [ 5.23112282e-01, -2.20157475e+00,  2.14459431e+00,
        -1.74945589e+00,  1.87784048e+00],
       [-1.73433252e+00, -1.49352464e+00, -4.92057103e+00,
        -1.38711472e+00,  3.35629381e+00],
       [-5.60021145e+00, -1.36451110e+00, -4.80308876e+00,
         5.14319192e+00,  2.58332232e+00],
       [-1.17829805e+00, -1.84722085e+00, -3.62910838e+00,
         1.62550287e-01,  2.55437587e+00],
       [-4.05444531e+00,  4.50513615e+00,  1.71482579e+00,
         2.42370374e+00, -1.48455118e+00],
       [ 3.43689555e+00,  7.13895810e-01, -6.92638269e-01,
        -4.35586376e+00, -1.94520748e+00],
       [-2.62693765e+00, -2.41880242e+00, -5.15056054e+00,
         7.25358153e-01

In [13]:
# calculate standard deviation of large sample.
stdev2 = sample2.std(axis=1)
stdev2 

array([2.45333633, 3.00768037, 4.07837007, 1.80200185, 2.64585396,
       4.15098739, 2.06984055, 3.02740298, 2.60547848, 2.56629166,
       2.33505003, 4.03613899, 1.89253732, 2.97627632, 1.31414499,
       3.17889856, 1.11913368, 2.56894236, 3.70778039, 2.55531212,
       1.95332904, 3.11157425, 3.52632368, 3.27192646, 2.4842577 ,
       1.96991936, 3.28837138, 1.16754681, 2.37832507, 3.14142866,
       3.11975289, 1.84484186, 4.57723655, 1.28545645, 2.20686267,
       3.56774703, 3.74477634, 1.4385523 , 2.56741363, 1.69081228,
       1.76020846, 1.65801643, 1.76936659, 3.16157035, 3.23371394,
       2.396293  , 4.0865834 , 3.47161123, 2.29735929, 4.48259503,
       3.46532186, 3.17171368, 4.63854701, 1.65648011, 2.82795365,
       2.40808035, 3.76642496, 1.8908272 , 0.80505002, 2.78504931,
       1.6085191 , 1.7524556 , 2.50550256, 1.31217707, 1.6358969 ,
       4.01478284, 2.88163102, 3.14272549, 0.93693686, 1.65868282,
       1.51587506, 2.58468034, 1.40553833, 2.2059486 , 2.23332

In [21]:
# show Bessel's correction n/n-1 is bigger in smaller sample sizes.
x = sample1
ncorr1 = np.mean (np.square(x- np.mean(x)))
ncorr1

5.4983254283601495

In [22]:
x = sample1
corr1 = np.mean (np.square(x- np.mean(x)))*(len(x)/ (len(x)-1))
corr1

6.109250475955722

In [ ]:
## minus from each other, do same with large sample. More explaination needed+plot

## References

https://www.verywellmind.com/what-is-a-confirmation-bias-2795024
https://nesslabs.com/authority-bias#:~:text=The%20authority%20bias%20is%20our,a%20reasonable%20thing%20to%20do.

https://www.nudgingfinancialbehaviour.com/overconfidence-bias-in-decision-making/